apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "cloudflared.fullname" . }}-tunnel
  labels:
    {{ include "cloudflared.labels" . | nindent 4 }}
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      {{ include "cloudflared.tunnelSelectorLabels" . | nindent 6 }}
